# Data

In [1]:
data = {
    'Gender': ['Male', 'Female', 'Female', 'Male', 'Female'],
    'City': ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Delhi'],
    'Size': ['Small', 'Large', 'Medium', 'Large', 'Small'],
    'Age': [25, 45, 32, 60, 28],
    'Fare': [15, 300, 85, 450, 20]
}

# Task 1 — Categorical Encoding

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.DataFrame(data)

# Label Encoding
le = LabelEncoder()
df['Gender'] = le.fit_transform(df['Gender']) # Male - 1, Female - 0

# One-Hot Encoding
df = pd.get_dummies(df, columns=['City'], drop_first=True)

# Ordinal Encoding
size_mapping = {'Small':0, 'Medium':1, 'Large':2}
df['Size'] = df['Size'].map(size_mapping)

df

   Gender  Size  Age  Fare  City_Delhi  City_Mumbai
0       1     0   25    15       False         True
1       0     2   45   300        True        False
2       0     1   32    85       False        False
3       1     2   60   450       False         True
4       0     0   28    20        True        False

Categorical features were converted into numerical form to make them suitable for machine learning models.

The Gender column was encoded using label encoding since it contains only two categories.

The City column was encoded using one-hot encoding because it has no natural order, and one column was dropped to avoid multicollinearity (dummy variable trap).

The Size column was encoded using ordinal encoding with a defined order (Small = 0, Medium = 1, Large = 2) to preserve its meaningful ranking.

# Task 2 — Feature Scaling

In [3]:
from sklearn.preprocessing import RobustScaler

scaler = RobustScaler()

# Applying Robust Scaler To Age And Fare Columns
# Because It Uses Median and IQR, Which is Less Sensitive to Outliers
# So The Median Value Becomes 0 And Value Below Median Becomes Negative and, Value Above Median Becomes Positive
df[['Age', 'Fare']] = scaler.fit_transform(df[['Age', "Fare"]])

df

   Gender  Size       Age      Fare  City_Delhi  City_Mumbai
0       1     0 -0.411765 -0.250000       False         True
1       0     2  0.764706  0.767857        True        False
2       0     1  0.000000  0.000000       False        False
3       1     2  1.647059  1.303571       False         True
4       0     0 -0.235294 -0.232143        True        False

Feature scaling was applied to the Age and Fare columns to bring them to a comparable scale.

Since the Fare column contains an outlier, RobustScaler was used because it is less sensitive to extreme values.

It scales data using the median and interquartile range, making it more suitable than other scalers for this dataset.